# Regression Table #


In [2]:
import pandas as pd
import statsmodels.api as sm
import numpy as np
from sklearn.model_selection import train_test_split

In [9]:
#### importing a dataset from kaggle
path_t0_data    =    "/home/jwalitnpanchal/college_work/sem10/ML_AI/case_studies/gold_price_forecasting_dataset.csv"
data1           =    pd.read_csv(path_t0_data)
#print(data1.info())
print(data1.head())

         date    adj close        close         high          low  \
0  2021-06-11  1877.400024  1877.400024  1902.300049  1875.199951   
1  2021-06-14  1864.000000  1864.000000  1866.599976  1846.500000   
2  2021-06-15  1854.500000  1854.500000  1867.199951  1854.400024   
3  2021-06-16  1859.500000  1859.500000  1860.099976  1809.199951   
4  2021-06-17  1773.800049  1773.800049  1823.300049  1769.599976   

          open  volume         ma_7        ma_30        ma_90  daily_return  \
0  1900.900024     349  1887.828561  1860.180005  1790.618891     -0.008869   
1  1866.199951      41  1886.799997  1863.403337  1790.972225     -0.007138   
2  1866.400024      78  1881.757132  1865.506669  1791.701114     -0.005097   
3  1859.400024     117  1876.428554  1868.296667  1792.241113      0.002696   
4  1811.800049    1135  1859.514282  1867.953337  1791.595558     -0.046088   

   volatility_7  volatility_30        rsi       macd  macd_signal  \
0      0.009353       0.007538  54.722931

In [7]:
###### extracting some predictors and one response
# predictors
opening_price    =    np.asarray(data1["open"].values).reshape(-1,1)
trade_volume     =    np.asarray(data1["volume"].values).reshape(-1,1)
ma_7_arr         =    np.asarray(data1["ma_7"].values).reshape(-1,1)
volatility_7_arr =    np.asarray(data1["volatility_7"].values).reshape(-1,1)
# response
daily_ret_arr    =    np.asarray(data1["daily_return"].values).reshape(-1,1)
######### stack the predictors into one matrix
predictor_stack =    np.column_stack((opening_price,trade_volume, ma_7_arr, volatility_7_arr))
print(predictor_stack)
predictor_stack       =    sm.add_constant(predictor_stack)
### split the data into parts
predictors_train, predictors_test, daily_ret_train, daily_ret_test    =    train_test_split(predictor_stack, daily_ret_arr, random_state=45, test_size=0.25)
######## train the model on the train dat:
print(daily_ret_train.shape, predictors_train.shape)
model_gold_pricing     =    sm.OLS(daily_ret_train, predictors_train)
fit_model_gold_pricing =    model_gold_pricing.fit()
print(fit_model_gold_pricing.summary())

[[1.90090002e+03 3.49000000e+02 1.88782856e+03 9.35330708e-03]
 [1.86619995e+03 4.10000000e+01 1.88680000e+03 6.41073817e-03]
 [1.86640002e+03 7.80000000e+01 1.88175713e+03 4.57208047e-03]
 ...
 [5.30160010e+03 1.12054000e+05 4.99108573e+03 1.48918955e-02]
 [5.41570020e+03 2.37090000e+04 5.07091427e+03 1.42146590e-02]
 [5.37639990e+03 2.37090000e+04 5.05407143e+03 5.11055932e-02]]
(875, 1) (875, 5)
                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.035
Model:                            OLS   Adj. R-squared:                  0.031
Method:                 Least Squares   F-statistic:                     7.907
Date:                Wed, 04 Feb 2026   Prob (F-statistic):           2.92e-06
Time:                        08:47:17   Log-Likelihood:                 2731.2
No. Observations:                 875   AIC:                            -5452.
Df Residuals:                     870   BIC: 

In [17]:
response_col    =    "daily_return"
predictors      =    data1.loc[:, data1.columns != response_col]
predictors      =    predictors.drop(columns="date")
predictors      =    sm.add_constant(predictors)
#print(predictors)
response        =    data1.loc[:, response_col]
### split the data into parts
predictors_train1, predictors_test1, daily_ret_train1, daily_ret_test1    =    train_test_split(predictors, response, random_state=45, test_size=0.25)

# fit the OLS model
model    =    sm.OLS(daily_ret_train1, predictors_train1)
results  =    model.fit()
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:           daily_return   R-squared:                       0.794
Model:                            OLS   Adj. R-squared:                  0.790
Method:                 Least Squares   F-statistic:                     220.6
Date:                Wed, 04 Feb 2026   Prob (F-statistic):          4.08e-282
Time:                        09:13:52   Log-Likelihood:                 3406.5
No. Observations:                 875   AIC:                            -6781.
Df Residuals:                     859   BIC:                            -6705.
Df Model:                          15                                         
Covariance Type:            nonrobust                                         
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const            -0.0105      0.002     -4.930