In [2]:
import numpy as np

In [23]:
# initialize the array whose pseudo-inverse is to be calculated
x    =    np.array([[1,1],[0,1],[1,0]])
#print(x.shape)
# performing the SVD on the above matrix using the inbuilt SVD function
U, S, Vt    =    np.linalg.svd(x)
print(U,"\n", S,"\n", Vt)

[[-8.16496581e-01 -1.85577521e-16 -5.77350269e-01]
 [-4.08248290e-01 -7.07106781e-01  5.77350269e-01]
 [-4.08248290e-01  7.07106781e-01  5.77350269e-01]] 
 [1.73205081 1.        ] 
 [[-0.70710678 -0.70710678]
 [ 0.70710678 -0.70710678]]


In [42]:
# calculating the pseudoinverse
# construct S_plus
S_plus    =    np.zeros((len(x[0,:]), len(x[:,0])))
for i in range(len(S)):
    S_plus[i,i]    =    1/S[i]
#print(S_plus)
x_plus    =    (Vt.T @ S_plus) @ U.T
print(x_plus)

[[ 0.33333333 -0.33333333  0.66666667]
 [ 0.33333333  0.66666667 -0.33333333]]


In [37]:
# checking if, indeed the above is pseudo-inverse of x or not
print(x_plus @ x)

[[ 1.00000000e+00  5.55111512e-17]
 [-5.55111512e-17  1.00000000e+00]]
