In [1]:
import numpy as np

In [2]:
x = np.array([[3,2,2],[2,3,-2]])
print(x)

[[ 3  2  2]
 [ 2  3 -2]]


In [3]:
u, sigma, vt   =   np.linalg.svd(x)
print(u,"\n",sigma,"\n",vt)

[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]] 
 [5. 3.] 
 [[-7.07106781e-01 -7.07106781e-01 -6.47932334e-17]
 [-2.35702260e-01  2.35702260e-01 -9.42809042e-01]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]]


In [15]:
# rank-1 decomposition of the matrix x
x_from_decom  =    np.zeros((x.shape[0],x.shape[1]))
sum_matrix    =    np.zeros((x.shape[0],x.shape[1]))
for k in range(sigma.shape[0]):
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            sum_matrix[i,j]    =    u[i,k] * vt[k,j]
    sum_matrix    =    sum_matrix/sigma[k]
    print(sum_matrix,"\n")
    x_from_decom  =    x_from_decom + sum_matrix

[[1.00000000e-01 1.00000000e-01 9.16314695e-18]
 [1.00000000e-01 1.00000000e-01 9.16314695e-18]] 

[[ 0.05555556 -0.05555556  0.22222222]
 [-0.05555556  0.05555556 -0.22222222]] 



In [16]:
print(x_from_decom)

[[ 0.15555556  0.04444444  0.22222222]
 [ 0.04444444  0.15555556 -0.22222222]]
